### ISSUE TITLE
Non-'.csproj' files don't get their output redirected

### ISSUE THREAD

**Issue by MarkSchofield** [craigktreasure/CentralBuildOutput#48]
When using the ['Microsoft.Build.NoTargets' MSBuild SDK](https://github.com/microsoft/MSBuildSdks/tree/main/src/NoTargets), project-file-relative `bin` and `obj` folders are created.

**Comment by MarkSchofield** [comment]
This may be similar to #18.

**Comment by MarkSchofield** [comment]
Ah. It's not that it's a "NoTargets" build, it's because I used a ".proj" file extension, and not a ".csproj" file extension. Moving back to a ".csproj" seems to fix things.

**Comment by MarkSchofield** [comment]
[`src/CentralBuildOutput/Sdk/ConfigureBuildOutput.props:116`](https://github.com/craigktreasure/CentralBuildOutput/blob/main/src/CentralBuildOutput/Sdk/ConfigureBuildOutput.props#L116) does this:

```msbuild
<CentralBuildOutputDotNetStyleProject Condition=" $(MSBuildProjectFile.EndsWith('.csproj')) ">true</CentralBuildOutputDotNetStyleProject>
```

Which means it only works with `.csproj` files. I'm not sure what this line is doing... :/

I'll update the title...

**Comment by craigktreasure** [comment]
Great catch! Any idea why someone would prefer `.proj` over `.csproj`? Curious why you did.

**Comment by MarkSchofield** [comment]
I believe both '.proj' and '.msbuildproj' are common-ish extensions for non-C# msbuild projects. VS's "Add existing project" lists "*.msbuildproj" in its open file dialog filter. I was using the NoTargets SDK (to kick off a CMake build) but VS still renders a "C#" icon and added the 'Dependencies' node (with Analyzers underneath) in the Solution Explorer. I'd changed the file extension to get a different icon and get rid of the "Analyzers" nodes.

**Comment by MarkSchofield** [comment]
Ah, and another '.csproj' vs '.proj' point: '.csproj' files discover Items by default, but '.proj' files don't (even with the NoTargets SDK). So if you've got a bunch of 'noise' within the '.csproj' scope it gets discovered by default and you have to opt-out with, say, `<None Remove="foo" />` it. But with a `.proj` or a `.msbuildproj`, nothing is discovered by default, and you have to opt-in with, say, `<None Include="bar" />`.

**Comment by craigktreasure** [comment]
So, i'm assuming you're intention is use the properties created by CentralBuildOutput to pass into a CMake command in your NoTargets project file. I can see how that would be useful. I'll add support for `*.proj` files. Hopefully it doesn't collide with some other `*.proj` assumptions.

**Comment by MarkSchofield** [comment]
I don’t think you even have to be that opinionated - you can still have central build output on-by-default just for csproj’s, just let me opt-in if I want to for .projs. At the minute ‘CentralBuildOutputDotNetStyleProject’ has to be true for things to work. Let me set, say, CentralBuildOutputEnabled to ‘true’ to opt-in.

**Comment by craigktreasure** [comment]
We can't do that on a per-project basis unfortunately. See #53.

**Comment by MarkSchofield** [comment]
But I can set something in Directory.Build.props. That sounds reasonable to me.

**Comment by craigktreasure** [comment]
Sure. But that sets it for everything, which isn't great if you have any other types of projects. I think I'll enable it for .proj files for now and we can revisit a better strategy when #53 is fixed. Sound reasonable?
